name: 'TreeStickies Create Index Action'
description: 'This action generates indexes of your TreeStickies repository. Notes are sorted by name. Cards are sorted by modified-date in descending order.'
inputs:
  timezone-offset-minutes:
    description: 'The timezone offset minutes of your locale. Default is 0 (UTC).'
    default: 0
  title-name:
    description: 'The title of the top index'
    default: 'INDEX'
  working-directory:
    description: 'Working directory name on the runner'
    default: '.'
runs:
  using: 'node12'
  main: 'index.js'
