name: 'TreeStickies Create Index Action'
description: 'This action generates index of your TreeStickies repository as README.md.'
inputs:
  index-file-name:
    description: 'The file name of the index'
    required: true
    default: 'README.md'
runs:
  using: 'node12'
  main: 'index.js'
